name: ci

env:
  BINARY_NAME: nest-secrets

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Run tests
        run: go test .
      - name: Build
        run: |
          GOOS=linux GOARCH=arm64 go build -o $BINARY_NAME-linux-arm64 main.go
          GOOS=linux GOARCH=amd64 go build -o $BINARY_NAME-linux-amd64 main.go
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ env.BINARY_NAME }}-*
